name: "CI examples"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  build:
    runs-on: macos-11
    defaults:
      run:
        working-directory: Examples
    steps:
    - uses: actions/checkout@v2
    - name: Xcode build
      run: make build-debug

